/*
Rawest Layer - Exploratory Data Analysis
Project: Hospital Warehouse Patient Analytics
Description: Key business insights from Rawest layer
*/

/*youngest patient*/
SELECT DISTINCT PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,AGE
FROM rawest.clean 
ORDER BY AGE ASC
LIMIT 5;

/*oldest patient*/
SELECT DISTINCT PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,AGE
FROM rawest.clean
ORDER BY AGE DESC
LIMIT 15;

/*first encounter date*/
SELECT ENCOUNTER_START,PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,AGE,BIRTHDATE,
GENDER,MARITAL,RACE,ETHNICITY,ENCOUNTER_DESCRIPTION
FROM rawest.clean
ORDER BY ENCOUNTER_START ASC
LIMIT 1;

/*last encounter date*/
SELECT ENCOUNTER_START AS LAST_ENCOUNTER_DATE,PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,AGE,BIRTHDATE,
GENDER,MARITAL,RACE,ETHNICITY,ENCOUNTER_DESCRIPTION
FROM rawest.clean
ORDER BY ENCOUNTER_START DESC
LIMIT 1;


/*first reported death*/
SELECT PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,DEATHDATE
FROM rawest.clean
WHERE DEATHDATE IS NOT NULL 
ORDER BY DEATHDATE ASC 
LIMIT 1;

/*latest death*/
SELECT PREFIX,FIRST_NAME,LAST_NAME,MAIDEN_NAME,DEATHDATE
FROM rawest.clean
WHERE DEATHDATE IS NOT NULL
ORDER BY DEATHDATE DESC
LIMIT 1;

/*total patients registerd*/
SELECT COUNT(DISTINCT FIRST_NAME,LAST_NAME,BIRTHDATE) AS TOTAL_PATIENTS
FROM rawest.clean;

/*total revenue*/
SELECT ROUND(SUM(TOTAL_CLAIM_COST),2) AS TOTAL_REVENUE
FROM rawest.clean;

/*total procedure cost*/
SELECT SUM(PROCEDURE_COST)AS TOTAL_PROCEDURE_COST
FROM rawest.clean;

/*total encounter cost*/
SELECT ROUND(SUM(BASE_ENCOUNTER_COST),2)AS TOTAL_ENCOUNTER_COST
FROM rawest.clean;

/*total deaths*/
SELECT  COUNT(DISTINCT CONCAT(FIRST_NAME,'-' ,LAST_NAME,'-',BIRTHDATE))AS TOTAL_DEATHS
FROM rawest.clean
WHERE DEATHDATE IS NOT NULL;

/*total patient by gender*/
SELECT GENDER,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS NUMBER_OF_PATIENTS
FROM rawest.clean
GROUP BY GENDER
ORDER BY COUNT(DISTINCT FIRST_NAME,LAST_NAME) DESC;

/*total patient by race*/
SELECT RACE,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS NUMBER_OF_PATIENTS
FROM rawest.clean
GROUP BY RACE
ORDER BY COUNT(DISTINCT FIRST_NAME,LAST_NAME) DESC;

/*total patient per each city*/
SELECT CITY,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS NO_OF_PATIENTS
FROM rawest.clean
GROUP BY CITY
ORDER BY COUNT(DISTINCT FIRST_NAME,LAST_NAME) DESC;

/*total patient per ethnicity*/
SELECT ETHNICITY,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS NO_OF_PATIENTS
FROM rawest.clean
GROUP BY ETHNICITY
ORDER BY COUNT(DISTINCT FIRST_NAME,LAST_NAME) DESC;

/*total patient per status and gender if maried and male or female or not yet maried*/
SELECT MARITAL,GENDER,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS NO_OF_PATIENTS
FROM rawest.clean
GROUP BY MARITAL,GENDER
ORDER BY COUNT(DISTINCT FIRST_NAME,LAST_NAME) DESC;

/*average encounter cost of each encounterclass*/
SELECT ENCOUNTERCLASS,ROUND(AVG(BASE_ENCOUNTER_COST),2) AS AVERAGE_COST
FROM rawest.clean
GROUP BY ENCOUNTERCLASS
ORDER BY AVG(BASE_ENCOUNTER_COST) DESC;

/* the total payer coverage by  each payer*/
SELECT PAYER_NAME,ROUND(SUM(PAYER_COVERAGE),2)AS PAYER_COVERAGE
FROM rawest.clean
WHERE PAYER_NAME != 'NO_INSURANCE'
GROUP BY PAYER_NAME
ORDER BY ROUND(SUM(PAYER_COVERAGE),2) DESC;

/*top 10 patients with highest revenue*/
SELECT DISTINCT FIRST_NAME,LAST_NAME,MAIDEN_NAME,ROUND(SUM(TOTAL_CLAIM_COST),2) AS TOTAL_REVENUE
FROM rawest.clean
GROUP BY  FIRST_NAME,LAST_NAME,MAIDEN_NAME
ORDER BY ROUND(SUM(TOTAL_CLAIM_COST),2) DESC
LIMIT 10;

/*hospital patient volume perfomance over time*/
SELECT YEAR(ENCOUNTER_START)AS YEAR,COUNT(DISTINCT FIRST_NAME,LAST_NAME) AS PATIENTS,COUNT(PROCEDURE_START)AS PROCEDURES_DONE
FROM rawest.clean
GROUP BY YEAR(ENCOUNTER_START)
ORDER BY YEAR ;

/*total deaths per year*/
SELECT  YEAR (DEATHDATE) AS DEATH_YEAR,COUNT(DISTINCT CONCAT(FIRST_NAME,'-' ,LAST_NAME,'-',BIRTHDATE))AS TOTAL_DEATHS
FROM rawest.clean
WHERE DEATHDATE IS NOT NULL
GROUP BY YEAR (DEATHDATE)
ORDER BY DEATH_YEAR ;

/*total cumulation contribution per month*/
SELECT MONTH ,
TOTAL_REVENUE,
ROUND(SUM(TOTAL_REVENUE) OVER(ORDER BY MONTH),2) AS RUNNING_TOTAL_REVENUE
FROM(
SELECT DATE_FORMAT(ENCOUNTER_START,'%Y-%m') AS MONTH , ROUND(SUM(TOTAL_CLAIM_COST),2)AS TOTAL_REVENUE
FROM rawest.clean
GROUP BY DATE_FORMAT(ENCOUNTER_START,'%Y-%m')
)t;

/*total cumulative revenue contribution per year*/
SELECT YEAR ,
TOTAL_REVENUE,
ROUND(SUM(TOTAL_REVENUE) OVER(ORDER BY YEAR),2) AS RUNNING_TOTAL_REVENUE
FROM(
SELECT DATE_FORMAT(ENCOUNTER_START,'%Y') AS YEAR, ROUND(SUM(TOTAL_CLAIM_COST),2)AS TOTAL_REVENUE
FROM rawest.clean
GROUP BY DATE_FORMAT(ENCOUNTER_START,'%Y')
)t;


/*total cumulative patients per year*/
SELECT YEAR ,
TOTAL_PATIENTS,
SUM(TOTAL_PATIENTS) OVER(ORDER BY YEAR) AS RUNNING_TOTAL_PATIENTS
FROM(
SELECT DATE_FORMAT(ENCOUNTER_START,'%Y') AS YEAR, COUNT(DISTINCT FIRST_NAME,LAST_NAME)AS TOTAL_PATIENTS
FROM rawest.clean
GROUP BY DATE_FORMAT(ENCOUNTER_START,'%Y')
)t;

/*total patients per year per encounterclass and the revenue generated*/
SELECT DATE_FORMAT(ENCOUNTER_START,'%Y') AS YEAR,ENCOUNTERCLASS, COUNT(DISTINCT FIRST_NAME,LAST_NAME)AS TOTAL_PATIENTS,
ROUND(SUM(TOTAL_CLAIM_COST),2)AS TOTAL_REVENUE
FROM rawest.clean
GROUP BY DATE_FORMAT(ENCOUNTER_START,'%Y'),ENCOUNTERCLASS
ORDER BY DATE_FORMAT(ENCOUNTER_START,'%Y');


/*age group and gender with the highest number of patients registerd*/
SELECT COUNT( DISTINCT FIRST_NAME,LAST_NAME) AS NO_OF_PATIENTS,AGE_GROUP,GENDER
FROM rawest.clean
GROUP BY AGE_GROUP,GENDER
ORDER BY COUNT( DISTINCT FIRST_NAME,LAST_NAME)DESC;

/*compare age group and gender with the highest number of deaths*/
SELECT COUNT(DISTINCT CONCAT(FIRST_NAME,'-' ,LAST_NAME,'-',BIRTHDATE)) AS NO_OF_DEATHS,AGE_GROUP,GENDER
FROM rawest.clean
WHERE DEATHDATE IS NOT NULL
GROUP BY AGE_GROUP,GENDER
ORDER BY NO_OF_DEATHS DESC;

/*payer analysis*/
SELECT PAYER_NAME,COUNT(*)AS NO_OF_PAYMENT,ROUND(SUM(TOTAL_CLAIM_COST),2)AS TOTAL_PAYMENT
FROM rawest.clean
GROUP BY PAYER_NAME;
