/*
==========================================================================
DDL Script: Create rawer table
==========================================================================
Script purpose:
This script creates table in the rawer schema dropping existing table if they already exist.
Run this script to re-define the DDL structure of 'rawer' table
*/


DROP TABLE IF EXISTS rawer.patients;
CREATE TABLE rawer.patients(
Id VARCHAR (50),
BIRTHDATE DATE,
DEATHDATE DATE,
PREFIX VARCHAR(50),
FIRST VARCHAR(50),
LAST VARCHAR (50),
SUFFIX VARCHAR(50),
MAIDEN VARCHAR(50),
MARITAL VARCHAR(50),
RACE VARCHAR(50),
ETHNICITY VARCHAR(50),
GENDER VARCHAR(50),
BIRTHPLACE VARCHAR(50),
ADDRESS VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
COUNTY VARCHAR(50),
ZIP VARCHAR(50),
LAT FLOAT,
LON FLOAT);


DROP TABLE IF EXISTS rawer.encounters;
CREATE TABLE rawer.encounters(
Id VARCHAR(50),
START VARCHAR(50),
STOP VARCHAR(50),
PATIENT VARCHAR(50),
ORGANIZATION VARCHAR(50),
PAYER VARCHAR(50),
ENCOUNTERCLASS VARCHAR(50),
CODE INT,
DESCRIPTION VARCHAR(100),
BASE_ENCOUNTER_COST FLOAT,
TOTAL_CLAIM_COST FLOAT,
PAYER_COVERAGE FLOAT,
REASONCODE VARCHAR(50),
REASONDESCRIPTION VARCHAR(50));

DROP TABLE IF EXISTS rawer.procedures;
CREATE TABLE rawer.procedures(
START DATETIME,
STOP DATETIME,
PATIENT VARCHAR(50),
ENCOUNTER VARCHAR(50),
CODE INT,
DESCRIPTION VARCHAR(100),
BASE_COST INT,
REASONCODE VARCHAR(50),
REASONDESCRIPTION VARCHAR(50));

DROP TABLE IF EXISTS rawer.payers;
CREATE TABLE rawer.payers(
Id VARCHAR(50),
NAME VARCHAR(50),
ADDRESS VARCHAR(50),
CITY VARCHAR(50),
STATE_HEADQUARTERED VARCHAR(50),
ZIP INT,
PHONE VARCHAR(50));
